version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data
    environment:
      - POSTGRES_DB=postgres10
      - POSTGRES_USER=postgres10
      - POSTGRES_PASSWORD=postgres10
  web: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    depends_on:
      - db 
